import type { Card } from "@/types";

/**
 * MyCreditCardinal V1 card database — 24 cards.
 *
 * earn_json: multipliers per category (1 = 1x/1%). All 12 category IDs present.
 * caps_json: monthly dollar spend caps per category (omit = no cap).
 *            "custom" key = monthly combined cap for custom-select categories.
 * rot_cap:   quarterly dollar cap for rotating bonus portion (rotating cards only).
 * color_json: CSS color stops for the card face gradient [from, to] or [from, via, to].
 */
export const CARDS: Card[] = [
  // ─── CHASE ────────────────────────────────────────────────────────────────

  {
    id: "csr",
    name: "Sapphire Reserve",
    issuer: "Chase",
    network: "Visa",
    currency: "chase_ur",
    fee: 550,
    earn_json: {
      dining: 3, groceries: 1, gas: 1,
      travel: 3, hotels: 3, streaming: 1,
      online: 1, entertainment: 1, transit: 3,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 60000, spend_requirement: 4000, timeframe_months: 3 },
    sub_hi_json: { points: 100000, spend_requirement: 4000, timeframe_months: 3, year: 2023 },
    score: 95,
    perks_json: [
      { label: "Annual Travel Credit", value: "$300/yr", annual_credit: 300 },
      { label: "Priority Pass Lounge Access", value: "Unlimited" },
      { label: "Global Entry / TSA PreCheck", value: "$100 credit" },
      { label: "DashPass", value: "Complimentary" },
    ],
    color_json: ["#1a2744", "#2d4a8a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 720,
    status: "active",
  },

  {
    id: "csp",
    name: "Sapphire Preferred",
    issuer: "Chase",
    network: "Visa",
    currency: "chase_ur",
    fee: 95,
    earn_json: {
      dining: 3, groceries: 3, gas: 1,
      travel: 2, hotels: 2, streaming: 3,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 60000, spend_requirement: 4000, timeframe_months: 3 },
    sub_hi_json: { points: 80000, spend_requirement: 4000, timeframe_months: 3, year: 2021 },
    score: 82,
    perks_json: [
      { label: "Annual Hotel Credit", value: "$50/yr (Chase Travel)", annual_credit: 50 },
      { label: "DashPass", value: "Complimentary" },
      { label: "Trip Cancellation Insurance", value: "Up to $10k" },
    ],
    color_json: ["#1c3a6e", "#4a7fd4"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 700,
    status: "active",
  },

  {
    id: "cff",
    name: "Freedom Flex",
    issuer: "Chase",
    network: "Mastercard",
    currency: "chase_ur",
    fee: 0,
    earn_json: {
      dining: 3, groceries: 1, gas: 1,
      travel: 1, hotels: 1, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 3, other: 1,
    },
    caps_json: {},
    // rot_cap is the quarterly cap (in dollars) on the rotating 5x bonus portion
    sub_json: { points: 20000, spend_requirement: 500, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 500, timeframe_months: 3, year: 2024 },
    score: 78,
    perks_json: [
      { label: "5x Rotating Quarterly Categories", value: "Up to $1,500/quarter" },
      { label: "Cell Phone Protection", value: "Up to $800/claim" },
    ],
    color_json: ["#0a2459", "#1a4fa8"],
    rotating: true,
    rot_cap: 1500,
    rot_opts: ["dining", "groceries", "gas", "online", "entertainment", "transit", "drugstore", "streaming"],
    rotation_schedule: {
      "2026": {
        "Q1": ["groceries", "streaming"],
        "Q2": ["dining", "hotels"],
        "Q3": ["gas", "transit"],
        "Q4": ["online", "groceries"],
      },
    },
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  {
    id: "cfu",
    name: "Freedom Unlimited",
    issuer: "Chase",
    network: "Visa",
    currency: "chase_ur",
    fee: 0,
    earn_json: {
      dining: 3, groceries: 1, gas: 1,
      travel: 5, hotels: 5, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 3, other: 1.5,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 500, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 500, timeframe_months: 3, year: 2024 },
    score: 74,
    perks_json: [
      { label: "1.5x on Everything", value: "No category restrictions" },
      { label: "Purchase Protection", value: "Up to $500/claim" },
    ],
    color_json: ["#2c2c2c", "#5a5a5a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  {
    id: "amazon_prime",
    name: "Amazon Prime Visa",
    issuer: "Chase",
    network: "Visa",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 2, groceries: 5, gas: 2,
      travel: 1, hotels: 1, streaming: 1,
      online: 5, entertainment: 1, transit: 2,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 0, timeframe_months: 0 },
    sub_hi_json: { points: 20000, spend_requirement: 0, timeframe_months: 0, year: 2024 },
    score: 70,
    perks_json: [
      { label: "5% at Amazon & Whole Foods", value: "Requires Prime membership" },
      { label: "$100 Amazon Gift Card", value: "On approval" },
    ],
    color_json: ["#1a1a1a", "#f90"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  // ─── AMEX ─────────────────────────────────────────────────────────────────

  {
    id: "amex_plat",
    name: "Platinum Card",
    issuer: "Amex",
    network: "Amex",
    currency: "amex_mr",
    fee: 695,
    earn_json: {
      dining: 1, groceries: 1, gas: 1,
      travel: 5, hotels: 5, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 80000, spend_requirement: 8000, timeframe_months: 6 },
    sub_hi_json: { points: 150000, spend_requirement: 15000, timeframe_months: 6, year: 2022 },
    score: 90,
    perks_json: [
      { label: "Airline Fee Credit", value: "$200/yr", annual_credit: 200 },
      { label: "Hotel Credit", value: "$200/yr (Fine Hotels)", annual_credit: 200 },
      { label: "Walmart+ / Digital Entertainment", value: "$240/yr", annual_credit: 240 },
      { label: "Lounge Access", value: "Centurion, Priority Pass, Delta" },
      { label: "Global Entry / TSA PreCheck", value: "$100 credit" },
      { label: "Saks Fifth Avenue", value: "$100/yr", annual_credit: 100 },
    ],
    color_json: ["#8a8a8a", "#c8c8c8", "#e8e8e8"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 720,
    status: "active",
  },

  {
    id: "amex_gold",
    name: "Gold Card",
    issuer: "Amex",
    network: "Amex",
    currency: "amex_mr",
    fee: 250,
    earn_json: {
      dining: 4, groceries: 4, gas: 1,
      travel: 3, hotels: 1, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    // Dining capped at $50k/yr (~$4167/mo); groceries at $25k/yr (~$2083/mo)
    caps_json: { dining: 4167, groceries: 2083 },
    sub_json: { points: 60000, spend_requirement: 4000, timeframe_months: 6 },
    sub_hi_json: { points: 90000, spend_requirement: 4000, timeframe_months: 6, year: 2023 },
    score: 88,
    perks_json: [
      { label: "Dining Credit", value: "$120/yr (GrubHub/etc)", annual_credit: 120 },
      { label: "Uber Cash", value: "$120/yr", annual_credit: 120 },
      { label: "Dunkin' Credit", value: "$84/yr", annual_credit: 84 },
      { label: "Resy Credit", value: "$100/yr", annual_credit: 100 },
    ],
    color_json: ["#c9940a", "#e8b82a", "#f5d060"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 700,
    status: "active",
  },

  {
    id: "amex_bcp",
    name: "Blue Cash Preferred",
    issuer: "Amex",
    network: "Amex",
    currency: "cash",
    fee: 95,
    earn_json: {
      dining: 1, groceries: 6, gas: 3,
      travel: 1, hotels: 1, streaming: 6,
      online: 1, entertainment: 1, transit: 3,
      rent: 1, drugstore: 1, other: 1,
    },
    // Groceries 6% capped at $6,000/yr → $500/mo
    caps_json: { groceries: 500 },
    sub_json: { points: 25000, spend_requirement: 3000, timeframe_months: 6 },
    sub_hi_json: { points: 35000, spend_requirement: 3000, timeframe_months: 6, year: 2023 },
    score: 76,
    perks_json: [
      { label: "Disney Bundle Credit", value: "$84/yr ($7/mo)", annual_credit: 84 },
      { label: "Auto & Purchase Protection", value: "Included" },
    ],
    color_json: ["#003087", "#0057b8"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  {
    id: "amex_bce",
    name: "Blue Cash Everyday",
    issuer: "Amex",
    network: "Amex",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 1, groceries: 3, gas: 3,
      travel: 1, hotels: 1, streaming: 1,
      online: 3, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    // Groceries/online/gas each capped at $6,000/yr → $500/mo
    caps_json: { groceries: 500, online: 500, gas: 500 },
    sub_json: { points: 20000, spend_requirement: 2000, timeframe_months: 6 },
    sub_hi_json: { points: 20000, spend_requirement: 2000, timeframe_months: 6, year: 2024 },
    score: 62,
    perks_json: [
      { label: "Disney Bundle Credit", value: "$84/yr ($7/mo)", annual_credit: 84 },
      { label: "Home Chef Credit", value: "$84/yr ($7/mo)", annual_credit: 84 },
    ],
    color_json: ["#003087", "#4a90d9"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  // ─── CAPITAL ONE ──────────────────────────────────────────────────────────

  {
    id: "c1_venturex",
    name: "Venture X",
    issuer: "Capital One",
    network: "Visa",
    currency: "cap1",
    fee: 395,
    earn_json: {
      dining: 2, groceries: 2, gas: 2,
      travel: 5, hotels: 10, streaming: 2,
      online: 2, entertainment: 2, transit: 2,
      rent: 2, drugstore: 2, other: 2,
    },
    caps_json: {},
    sub_json: { points: 75000, spend_requirement: 4000, timeframe_months: 3 },
    sub_hi_json: { points: 75000, spend_requirement: 4000, timeframe_months: 3, year: 2024 },
    score: 85,
    perks_json: [
      { label: "Annual Travel Credit", value: "$300/yr (C1 Travel)", annual_credit: 300 },
      { label: "Anniversary Bonus", value: "10,000 miles/yr" },
      { label: "Priority Pass + Capital One Lounges", value: "Unlimited" },
      { label: "Global Entry / TSA PreCheck", value: "$100 credit" },
    ],
    color_json: ["#0a0a0a", "#1a1a2e", "#2d2d44"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 720,
    status: "active",
  },

  {
    id: "c1_venture",
    name: "Venture",
    issuer: "Capital One",
    network: "Visa",
    currency: "cap1",
    fee: 95,
    earn_json: {
      dining: 2, groceries: 2, gas: 2,
      travel: 5, hotels: 5, streaming: 2,
      online: 2, entertainment: 2, transit: 2,
      rent: 2, drugstore: 2, other: 2,
    },
    caps_json: {},
    sub_json: { points: 75000, spend_requirement: 4000, timeframe_months: 3 },
    sub_hi_json: { points: 75000, spend_requirement: 4000, timeframe_months: 3, year: 2024 },
    score: 72,
    perks_json: [
      { label: "Global Entry / TSA PreCheck", value: "$100 credit" },
      { label: "2x on Everything", value: "No category restrictions" },
    ],
    color_json: ["#1c1c2e", "#4a4a7a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 700,
    status: "active",
  },

  {
    id: "c1_savorone",
    name: "SavorOne",
    issuer: "Capital One",
    network: "Mastercard",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 3, groceries: 3, gas: 1,
      travel: 1, hotels: 1, streaming: 3,
      online: 1, entertainment: 3, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 500, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 500, timeframe_months: 3, year: 2024 },
    score: 65,
    perks_json: [
      { label: "3% on Dining, Entertainment, Streaming", value: "No annual fee" },
    ],
    color_json: ["#0d0d0d", "#2a0a0a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  {
    id: "c1_quicksilver",
    name: "Quicksilver",
    issuer: "Capital One",
    network: "Mastercard",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 1.5, groceries: 1.5, gas: 1.5,
      travel: 1.5, hotels: 1.5, streaming: 1.5,
      online: 1.5, entertainment: 1.5, transit: 1.5,
      rent: 1.5, drugstore: 1.5, other: 1.5,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 500, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 500, timeframe_months: 3, year: 2024 },
    score: 55,
    perks_json: [
      { label: "1.5% on Everything", value: "No annual fee" },
    ],
    color_json: ["#3a3a3a", "#7a7a7a", "#b0b0b0"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  // ─── CITI ─────────────────────────────────────────────────────────────────

  {
    id: "citi_strata_premier",
    name: "Strata Premier",
    issuer: "Citi",
    network: "Mastercard",
    currency: "citi_typ",
    fee: 95,
    earn_json: {
      dining: 3, groceries: 3, gas: 3,
      travel: 3, hotels: 3, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 75000, spend_requirement: 4000, timeframe_months: 3 },
    sub_hi_json: { points: 100000, spend_requirement: 4000, timeframe_months: 3, year: 2023 },
    score: 80,
    perks_json: [
      { label: "Annual Hotel Savings Benefit", value: "$100 off $500+ hotel booking" },
      { label: "Transfer Partners", value: "17+ airline & hotel programs" },
    ],
    color_json: ["#0a1628", "#1a3a6e"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 700,
    status: "active",
  },

  {
    id: "citi_strata_elite",
    name: "Strata Elite",
    issuer: "Citi",
    network: "Mastercard",
    currency: "citi_typ",
    fee: 595,
    earn_json: {
      dining: 3, groceries: 1, gas: 1,
      travel: 10, hotels: 8, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 125000, spend_requirement: 15000, timeframe_months: 3 },
    sub_hi_json: { points: 125000, spend_requirement: 15000, timeframe_months: 3, year: 2024 },
    score: 78,
    perks_json: [
      { label: "Lounge Access", value: "Priority Pass Select" },
      { label: "Annual Travel Credit", value: "$250/yr", annual_credit: 250 },
      { label: "Global Entry / TSA PreCheck", value: "$120 credit" },
    ],
    color_json: ["#0a0a14", "#1a1a2e", "#2a2a4a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 720,
    status: "active",
  },

  {
    id: "citi_custom_cash",
    name: "Custom Cash",
    issuer: "Citi",
    network: "Mastercard",
    currency: "citi_typ",
    fee: 0,
    earn_json: {
      dining: 1, groceries: 1, gas: 1,
      travel: 1, hotels: 1, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    // 5% on top eligible category capped at $500/mo
    caps_json: { custom: 500 },
    sub_json: { points: 20000, spend_requirement: 1500, timeframe_months: 6 },
    sub_hi_json: { points: 20000, spend_requirement: 1500, timeframe_months: 6, year: 2024 },
    score: 68,
    perks_json: [
      { label: "5% on Top Category", value: "Auto-detects highest spend, up to $500/mo" },
    ],
    color_json: ["#f5f5f5", "#e0e0e0"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: true,
    custom_max: 1,
    custom_rate: 5,
    custom_opts: ["dining", "groceries", "gas", "transit", "streaming", "drugstore", "online", "entertainment"],
    fico_min: 670,
    status: "active",
  },

  {
    id: "citi_double_cash",
    name: "Double Cash",
    issuer: "Citi",
    network: "Mastercard",
    currency: "citi_typ",
    fee: 0,
    earn_json: {
      dining: 2, groceries: 2, gas: 2,
      travel: 2, hotels: 2, streaming: 2,
      online: 2, entertainment: 2, transit: 2,
      rent: 2, drugstore: 2, other: 2,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 1500, timeframe_months: 6 },
    sub_hi_json: { points: 20000, spend_requirement: 1500, timeframe_months: 6, year: 2024 },
    score: 60,
    perks_json: [
      { label: "2% on Everything", value: "1% on purchase + 1% on payment" },
    ],
    color_json: ["#1a3a6e", "#2d5aaa"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  // ─── DISCOVER ─────────────────────────────────────────────────────────────

  {
    id: "discover_it",
    name: "Discover it Cash Back",
    issuer: "Discover",
    network: "Discover",
    currency: "discover",
    fee: 0,
    earn_json: {
      dining: 1, groceries: 1, gas: 1,
      travel: 1, hotels: 1, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 0, spend_requirement: 0, timeframe_months: 12 },
    sub_hi_json: { points: 0, spend_requirement: 0, timeframe_months: 12, year: 2024 },
    score: 58,
    perks_json: [
      { label: "5x Rotating Quarterly Categories", value: "Up to $1,500/quarter" },
      { label: "Cashback Match", value: "First year — all rewards doubled" },
      { label: "No Annual Fee", value: "No foreign transaction fee" },
    ],
    color_json: ["#e8e8e8", "#f5a623", "#e8e8e8"],
    rotating: true,
    rot_cap: 1500,
    rot_opts: ["dining", "groceries", "gas", "online", "entertainment", "transit", "drugstore", "streaming"],
    rotation_schedule: {
      "2026": {
        "Q1": ["groceries", "drugstore"],
        "Q2": ["gas", "transit"],
        "Q3": ["dining", "online"],
        "Q4": ["online", "groceries"],
      },
    },
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 650,
    status: "active",
  },

  // ─── US BANK ──────────────────────────────────────────────────────────────

  {
    id: "usb_cash_plus",
    name: "Cash+",
    issuer: "US Bank",
    network: "Visa",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 1, groceries: 1, gas: 1,
      travel: 1, hotels: 1, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    // 5% on 2 chosen categories, capped at $2,000/quarter (~$667/mo combined)
    caps_json: { custom: 667 },
    sub_json: { points: 20000, spend_requirement: 1000, timeframe_months: 4 },
    sub_hi_json: { points: 20000, spend_requirement: 1000, timeframe_months: 4, year: 2024 },
    score: 64,
    perks_json: [
      { label: "5% on 2 Chosen Categories", value: "Up to $2,000/quarter combined" },
      { label: "2% on 1 Everyday Category", value: "Groceries, restaurants, or gas" },
    ],
    color_json: ["#8b0000", "#cc0000"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: true,
    custom_max: 2,
    custom_rate: 5,
    custom_opts: ["streaming", "entertainment", "transit", "dining", "online", "drugstore"],
    fico_min: 670,
    status: "active",
  },

  // ─── WELLS FARGO ──────────────────────────────────────────────────────────

  {
    id: "wf_autograph",
    name: "Autograph",
    issuer: "Wells Fargo",
    network: "Visa",
    currency: "wf",
    fee: 0,
    earn_json: {
      dining: 3, groceries: 1, gas: 3,
      travel: 3, hotels: 3, streaming: 3,
      online: 1, entertainment: 1, transit: 3,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 30000, spend_requirement: 1500, timeframe_months: 3 },
    sub_hi_json: { points: 30000, spend_requirement: 1500, timeframe_months: 3, year: 2024 },
    score: 63,
    perks_json: [
      { label: "3x on 6 Categories", value: "No annual fee" },
      { label: "Cell Phone Protection", value: "Up to $600/claim" },
    ],
    color_json: ["#6b1a1a", "#c0392b"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  {
    id: "wf_active_cash",
    name: "Active Cash",
    issuer: "Wells Fargo",
    network: "Visa",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 2, groceries: 2, gas: 2,
      travel: 2, hotels: 2, streaming: 2,
      online: 2, entertainment: 2, transit: 2,
      rent: 2, drugstore: 2, other: 2,
    },
    caps_json: {},
    sub_json: { points: 20000, spend_requirement: 500, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 500, timeframe_months: 3, year: 2024 },
    score: 57,
    perks_json: [
      { label: "2% on Everything", value: "No annual fee" },
      { label: "Cell Phone Protection", value: "Up to $600/claim" },
    ],
    color_json: ["#4a0000", "#8b1a1a"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 670,
    status: "active",
  },

  // ─── BANK OF AMERICA ──────────────────────────────────────────────────────

  {
    id: "boa_ccr",
    name: "Customized Cash Rewards",
    issuer: "Bank of America",
    network: "Visa",
    currency: "cash",
    fee: 0,
    earn_json: {
      dining: 2, groceries: 2, gas: 2,
      travel: 1, hotels: 1, streaming: 1,
      online: 2, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    // 3% on chosen category + 2% on groceries/wholesale — combined cap $2,500/quarter (~$833/mo)
    caps_json: { custom: 833, groceries: 833 },
    sub_json: { points: 20000, spend_requirement: 1000, timeframe_months: 3 },
    sub_hi_json: { points: 20000, spend_requirement: 1000, timeframe_months: 3, year: 2024 },
    score: 61,
    perks_json: [
      { label: "3% Chosen Category", value: "Gas, online, dining, travel, drugstore, or home improvement" },
      { label: "2% Groceries & Wholesale Clubs", value: "Up to $2,500/quarter combined with 3%" },
      { label: "Preferred Rewards Boost", value: "Up to 75% more rewards" },
    ],
    color_json: ["#8b0000", "#b22222", "#cc3333"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: true,
    custom_max: 1,
    custom_rate: 3,
    custom_opts: ["gas", "online", "dining", "travel", "drugstore"],
    fico_min: 670,
    status: "active",
  },

  // ─── BILT ─────────────────────────────────────────────────────────────────

  {
    id: "bilt",
    name: "Bilt Mastercard",
    issuer: "Bilt",
    network: "Mastercard",
    currency: "bilt",
    fee: 0,
    earn_json: {
      dining: 3, groceries: 1, gas: 1,
      travel: 2, hotels: 2, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 1, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: null,
    sub_hi_json: null,
    score: 73,
    perks_json: [
      { label: "1x on Rent — No Transaction Fee", value: "Up to $50k/yr" },
      { label: "Rent Day (1st of Month)", value: "2x on all non-rent spend" },
      { label: "Transfer Partners", value: "Airline & hotel points at 1:1" },
    ],
    color_json: ["#1a1a1a", "#2d2d2d", "#404040"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 700,
    status: "active",
  },

  {
    id: "bilt_palladium",
    name: "Bilt Palladium",
    issuer: "Bilt",
    network: "Mastercard",
    currency: "bilt",
    fee: 550,
    earn_json: {
      dining: 6, groceries: 1, gas: 1,
      travel: 3, hotels: 3, streaming: 1,
      online: 1, entertainment: 1, transit: 1,
      rent: 2, drugstore: 1, other: 1,
    },
    caps_json: {},
    sub_json: { points: 50000, spend_requirement: 5000, timeframe_months: 3 },
    sub_hi_json: { points: 50000, spend_requirement: 5000, timeframe_months: 3, year: 2024 },
    score: 69,
    perks_json: [
      { label: "2x on Rent — No Transaction Fee", value: "Up to $50k/yr" },
      { label: "6x Dining", value: "Best dining rate on the market" },
      { label: "Lounge Access", value: "Priority Pass" },
      { label: "Global Entry / TSA PreCheck", value: "$120 credit" },
    ],
    color_json: ["#4a3728", "#8b6914", "#c9a84c"],
    rotating: false, rot_cap: null, rot_opts: null,
    custom_select: false, custom_max: null, custom_rate: null, custom_opts: null,
    fico_min: 720,
    status: "active",
  },
];

export default CARDS;
